### PR TITLE
fix(admin): add JSON field editor in content forms

### LINKED ISSUE #405: JSON field type has no editor in admin UI
### Description

Selecting json as a field type in the schema editor works, but the field has no input renderer in the post editor — falls through to default text Input which renders empty for object values. Missing case in field renderer switch (@emdash-cms/admin@0.1.0)

### Steps to reproduce

1. Fresh install of `@emdash-cms/template-blog-cloudflare` (or any EmDash project on `emdash@0.1.0`)
2. Run `pnpm dev` and complete the setup wizard
3. Go to **Admin → Collections → Posts** (or any collection) → **Add field**
4. In the field type picker, select **JSON** (icon: brackets-curly, label: "JSON", description: "Arbitrary JSON data")
5. Fill in slug/label, save the field
6. Go to **Posts → New post** (or edit any existing post)
7. Scroll to the new JSON field

### Environment

- `emdash`: 0.1.0
- `@emdash-cms/admin`: 0.1.0
- `@emdash-cms/cloudflare`: 0.1.0
- `astro`: 6.1.4
- `@astrojs/cloudflare`: 13.1.7
- `wrangler`: 4.81.0
- Node: v22.22.2
- OS: Windows 11
- Browser: Chrome
- Template: `@emdash-cms/template-blog-cloudflare@0.0.1`

### Logs / error output

```shell

```

### PR DESCRIPTION
**Pull request by all3f0r1**
## What does this PR do?

The JSON field type was selectable in the schema editor, but had no dedicated input renderer in the content editor. It fell through to the default text `Input`, which rendered empty for object values since `typeof value === "string"` is false for objects.

This adds a `JsonFieldEditor` component that:
- Serializes object values to formatted JSON for display
- Parses user input back to a JS value on change
- Shows inline validation feedback for invalid JSON

Closes #405

## Type of change

- [x] Bug fix
- [ ] Feature (requires [approved Discussion](https://github.com/emdash-cms/emdash/discussions/categories/ideas))
- [ ] Refactor (no behavior change)
- [ ] Documentation
- [ ] Performance improvement
- [ ] Tests
- [ ] Chore (dependencies, CI, tooling)

## Checklist

- [x] I have read [CONTRIBUTING.md](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md)
- [x] `pnpm typecheck` passes
- [x] `pnpm --silent lint:json | jq '.diagnostics | length'` returns 0
- [x] `pnpm test` passes (or targeted tests for my change)
- [x] `pnpm format` has been run
- [x] I have added/updated tests for my changes (if applicable)
- [x] I have added a [changeset](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md#changesets) (if this PR changes a published package)
- [ ] New features link to an approved Discussion: https://github.com/emdash-cms/emdash/discussions/...

## AI-generated code disclosure

- [x] This PR includes AI-generated code

## Screenshots / test output

Two new tests added in `ContentEditor.test.tsx`:
- `renders json fields as a textarea` — verifies the JSON field renders a `<textarea>` element
- `renders json fields with object values as formatted JSON` — verifies object data is serialized as pretty-printed JSON

### CODE REVIEW

File: packages/admin/src/components/ContentEditor.tsx [hunk 1]
```diff
@@ -1261,6 +1170,64 @@ function FieldRenderer({
...
+			setError(null);
+			onChange(null);
+			return;
+		}
+		try {
+			const parsed = JSON.parse(newText);
+			setError(null);
+			onChange(parsed);
+		} catch {
+			setError("Invalid JSON");
```
Comment (ascorbic) [inline packages/admin/src/components/ContentEditor.tsx]:
```suggestion
			setError(t`Invalid JSON`);
```
...and import the Lingui hooks

File: packages/admin/src/components/ContentEditor.tsx [hunk 2]
```diff
@@ -1261,6 +1170,64 @@ function FieldRenderer({
...
+	const [text, setText] = React.useState(value);
+	const [error, setError] = React.useState<string | null>(null);
+
+	// Sync from parent when value changes externally
+	React.useEffect(() => {
+		setText(value);
+		setError(null);
+	}, [value]);
+
+	const handleChange = (newText: string) => {
```
Comment (ascorbic) [inline packages/admin/src/components/ContentEditor.tsx:1339]: I've not tested this, but isn't this quite hard to use? It will be reformatting while the user types. Maybe call this onBlur instead?

**Review by ascorbic — COMMENTED** [review]
Thanks! Just a couple of notes

File: packages/admin/src/components/ContentEditor.tsx (hunk 1 above)
Comment (all3f0r1) [reply packages/admin/src/components/ContentEditor.tsx]: Done.

File: packages/admin/src/components/ContentEditor.tsx (hunk 2 above)
Comment (all3f0r1) [reply packages/admin/src/components/ContentEditor.tsx:1339]: You're right. Change applied accordingly.

**Review by ascorbic — APPROVED** [review]
Great, thanks!
