### PR TITLE
fix: clone response before setting baseline security headers

### LINKED ISSUE #506: EmDash middleware mutates immutable Response headers on Cloudflare/Astro public routes
### Description

`src/astro/middleware.ts` calls `response.headers.set()` directly on the `Response` returned by `next()`.

https://github.com/emdash-cms/emdash/blob/e2f96aa74bd936832a3a4d0636e81f948adb51c7/packages/core/src/astro/middleware.ts#L247-L249

https://github.com/emdash-cms/emdash/blob/e2f96aa74bd936832a3a4d0636e81f948adb51c7/packages/core/src/astro/middleware.ts#L159-L177

On Cloudflare enviroment, some responses which is related to cache api appear to have immutable headers (for example `/_image/*`), which causes: `TypeError: Can't modify immutable headers.`

https://github.com/withastro/astro/blob/7fe40bc7381d981dedad16625d89c00e31cd8fd0/packages/integrations/cloudflare/src/entrypoints/image-transform-endpoint.ts#L8-L14

### Steps to reproduce

using `<Image />` component

astro.config.mjs:

```mjs
import cloudflare from '@astrojs/cloudflare'
import react from '@astrojs/react'
import { d1, r2, sandbox } from '@emdash-cms/cloudflare'
import { defineConfig } from 'astro/config'
import emdash from 'emdash/astro'

export default defineConfig({
	output: 'server',
	adapter: cloudflare({
		imageService: {
			build: 'compile',
                        runtime: 'cloudflare-binding',
		},
	}),
	image: {
		layout: 'constrained',
		responsiveStyles: true,
	},
	integrations: [
		react(),
		emdash({
			database: d1({ binding: 'DB', session: 'auto' }),
			storage: r2({ binding: 'MEDIA' }),
			sandboxRunner: sandbox(),
		}),
	],
	devToolbar: { enabled: false },
})
```

### Environment

- Astro: `6.1.5`
- EmDash: `0.1.1`
- `@astrojs/cloudflare`: `13.1.8`
- `@emdash-cms/cloudflare`: `0.1.1`

### Logs / error output

```shell
01:37:27 [vite] 01:37:26 [200] / 810ms
01:37:28 [vite] 01:37:28 [200] / 114ms
01:37:28 [vite] 01:37:28 [200] /_image 1248ms
01:37:29 [ERROR] [vite] 01:37:29 [ERROR] TypeError: Can't modify immutable headers.
      at setBaselineSecurityHeaders (.../node_modules/.vite/deps_ssr/emdash_middleware.js:1573:20)
      at .../node_modules/.vite/deps_ssr/emdash_middleware.js:1597:7
      at callMiddleware (.../chunk-AJ67EPPI.js:1035:10)
      at _RenderContext.render (.../chunk-AJ67EPPI.js:2079:73)
      at DevApp.render (.../chunk-AJ67EPPI.js:2989:20)
      at Object.handle [as fetch] (.../@astrojs_cloudflare_entrypoints_server.js:208:20)
```

### PR DESCRIPTION
**Pull request by mvanhorn**
## What does this PR do?

`setBaselineSecurityHeaders` in `packages/core/src/astro/middleware.ts` calls `response.headers.set()` directly on the Response returned by `next()`. On Cloudflare, some responses (e.g. `/_image/*` from Astro's image transform endpoint) have immutable headers, causing `TypeError: Can't modify immutable headers.`

This PR changes the function to create a new `Response` with cloned headers before modifying them. The original response body, status, and statusText are preserved. All three call sites in the middleware are updated.

Closes #506

## Type of change

- [x] Bug fix
- [ ] Feature (requires [maintainer-approved Discussion](https://github.com/emdash-cms/emdash/discussions/categories/ideas))
- [ ] Refactor (no behavior change)
- [ ] Translation
- [ ] Documentation
- [ ] Performance improvement
- [ ] Tests
- [ ] Chore (dependencies, CI, tooling)

## Checklist

- [x] I have read [CONTRIBUTING.md](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md)
- [x] `pnpm typecheck` passes
- [x] `pnpm lint` passes
- [x] `pnpm test` passes (or targeted tests for my change)
- [x] `pnpm format` has been run
- [x] I have added/updated tests for my changes (if applicable)
- [ ] User-visible strings in the admin UI are [wrapped for translation](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md#internationalization-i18n) and `pnpm locale:extract` has been run (if applicable)
- [x] I have added a [changeset](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md#changesets) (if this PR changes a published package)
- [ ] New features link to an approved Discussion: https://github.com/emdash-cms/emdash/discussions/...

## AI-generated code disclosure

- [x] This PR includes AI-generated code

## Screenshots / test output

`pnpm --silent lint:quick` returns 0 diagnostics.

### CODE REVIEW

File: packages/core/src/astro/middleware.ts [hunk 1]
```diff
@@ -160,20 +160,23 @@ async function getRuntime(config: EmDashConfig): Promise<EmDashRuntime> {
  * Baseline security headers applied to all responses.
  * Admin routes get additional headers (strict CSP) from auth middleware.
  */
-function setBaselineSecurityHeaders(response: Response): void {
+function setBaselineSecurityHeaders(response: Response): Response {
+	const headers = new Headers(response.headers);
```
Comment (hayatosc) [inline packages/core/src/astro/middleware.ts]: In [Using the Cache API](https://developers.cloudflare.com/workers/examples/cache-api/) on Cloudflare Docs , the approach of using `response = new Response(response.body, response)` is employed to clone a response.
Don't you think this method would be considered better?

Comment (mvanhorn) [reply packages/core/src/astro/middleware.ts]: Good call - updated in 3a1eeef to use `new Response(response.body, response)` per the Cloudflare docs pattern. Cleaner than manually extracting status/statusText.

**Review by ascorbic — APPROVED** [review]
Thanks!
