### PR TITLE
fix(admin): render multiSelect fields as checkbox group

### LINKED ISSUE #204: Multi Select custom fields render as standard inputs
### Description

The Multi Select custom field is rendered in the editor for the post type as a standard text `<input>` field with no options.

### Steps to reproduce

1. Create a custom post type
2. Add a Multi Select field to it with some options
3. Save and then create a post with that post type
4. Field simply renders as a standard text input box

### Environment

- Version 0.1.0
- Environment: locahost (Yarn with Vite)
- Browser: Chrome 146.0.7680.178

### Logs / error output

```shell

```

### PR DESCRIPTION
**Pull request by tsikatawill**
## What does this PR do?

The `FieldRenderer` switch in `ContentEditor.tsx` had no `case "multiSelect"`, so multiSelect custom fields fell through to the default case and rendered as plain text `<input>` elements. This adds a checkbox group renderer using the Kumo `Checkbox` component.

Closes #204

## Type of change

- [x] Bug fix
- [ ] Feature (requires [approved Discussion](https://github.com/emdash-cms/emdash/discussions/categories/ideas))
- [ ] Refactor (no behavior change)
- [ ] Documentation
- [ ] Performance improvement
- [ ] Tests
- [ ] Chore (dependencies, CI, tooling)

## Checklist

- [x] I have read [CONTRIBUTING.md](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md)
- [x] `pnpm typecheck` passes
- [x] `pnpm --silent lint:json | jq '.diagnostics | length'` returns 0
- [x] `pnpm test` passes (or targeted tests for my change)
- [x] `pnpm format` has been run
- [x] I have added/updated tests for my changes (if applicable)
- [x] I have added a [changeset](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md#changesets) (if this PR changes a published package)
- [ ] New features link to an approved Discussion: https://github.com/emdash-cms/emdash/discussions/...

## AI-generated code disclosure

- [x] This PR includes AI-generated code

## Screenshots / test output

All 3198 tests pass across all packages (admin: 710, core: 2095, cloudflare: 127, auth: 41, blocks: 60, gutenberg-to-portable-text: 100, marketplace: 48, x402: 17).

### CODE REVIEW

File: packages/admin/src/components/ContentEditor.tsx [hunk 1]
```diff
@@ -1116,6 +1117,33 @@ function FieldRenderer({
 			);
 		}
 
+		case "multiSelect": {
```
Comment (BenjaminPrice) [inline packages/admin/src/components/ContentEditor.tsx:1160]: **Nit**

field.options?.map silently renders an empty group if a multiSelect field is defined without options. This is acceptably defensive, but a schema-level validation requiring options on multiSelect fields would be more robust.

**Review by BenjaminPrice — APPROVED** [review]
Solid fix that correctly renders multiSelect fields as a checkbox group; all tested scenarios pass.

### Tested scenarios

- multiSelect field renders as checkboxes in the admin UI
- Checking values and saving persists the selection correctly
- Unchecking a value and saving reflects the updated selection
- Unchecking all values saves an empty array
- Autosave preserves multiSelect changes without data loss
- multiSelect field with no options defined renders gracefully without errors

**Review by ascorbic — APPROVED** [review]
Thanks!

**Comment by tsikatawill** [comment]
Happy to contribute
