### PR TITLE
fix(core): remove FTS5 integrity-check to prevent D1 shadow table corruption

### LINKED ISSUE #252: FTS5 integrity-check corrupts D1 shadow tables — publish fails with SQLITE_CORRUPT_VTAB on all collections
## Description
Publishing any content (posts, pages, custom collections) fails with 500 on Cloudflare D1. Saving drafts works fine. Affects every collection that has search enabled.

## Error
Content publish error: Error: D1_ERROR: database disk image is malformed: SQLITE_CORRUPT (extended: SQLITE_CORRUPT_VTAB)

## Root cause identified
The bug is in `FTSManager.verifyAndRepairIndex()` in `packages/core/src/search/fts-manager.ts`.

This line runs on every Worker startup:
INSERT INTO "ftsTable"("{ftsTable}"("
ftsTable"("{ftsTable}") VALUES('integrity-check')

This FTS5 integrity-check command corrupts D1's FTS5 shadow tables. After corruption, the FTS triggers fire on every content update and cause publish to fail.

## Workaround
Drop all FTS tables and triggers, then set search_config to disabled:
```sql
UPDATE _emdash_collections SET search_config = '{"enabled":false}' WHERE search_config IS NOT NULL;
```
Then drop all `_emdash_fts_*` tables and triggers manually via D1 console.

## Suggested fix
Skip the integrity-check INSERT on D1, or catch the corruption and drop/rebuild rather than leaving tables in a corrupted state.

## Environment
- emdash@0.1.0
- @emdash-cms/cloudflare@0.1.0
- Cloudflare D1 + paid Workers plan

## Steps to reproduce
1. Deploy EmDash to Cloudflare Workers with D1 database
2. Run setup wizard and create admin account
3. Create any collection with at least one searchable field
4. Create a content item in that collection and save as draft — works fine
5. Click Publish — fails with 500
6. Check Cloudflare Observability logs — shows SQLITE_CORRUPT_VTAB
7. Repeat for any collection (posts, pages, videos, custom) — all fail

## Additional notes
- The corruption happens on every Worker cold start because verifyAndRepairIndex() runs at startup
- The integrity-check INSERT leaves the FTS5 shadow tables in a corrupted state
- The corrupted triggers then fire on every content UPDATE, causing publish to fail
- Dropping the FTS tables and triggers manually restores publish functionality
- The issue recurs whenever EmDash recreates FTS tables for a new collection
- This affects ALL content publishing on D1 — making the CMS unusable for production on Cloudflare without the manual workaround

## Environment
- emdash: 0.1.0
- @emdash-cms/cloudflare: 0.1.0
- @emdash-cms/plugin-audit-log: 0.1.0
- @emdash-cms/plugin-forms: 0.1.0
- Cloudflare Workers (paid plan)
- Cloudflare D1 database
- Cloudflare R2 storage
- Cloudflare Worker Loader (Dynamic Workers)
- Wrangler: 4.80.0
- Node.js: 22.16.0
- Bun: 1.2.15

### Logs / error output

```shell
## Logs / error output
From Cloudflare Observability:

Content publish error: Error: D1_ERROR: database disk image is malformed: SQLITE_CORRUPT (extended: SQLITE_CORRUPT_VTAB)

Worker startup logs (repeating on every cold start):
FTS index for "pages" has 2 rows but content table has 1. Rebuilding.
Repaired 1 corrupted FTS index(es) at startup

Publish API call:
POST /_emdash/api/content/posts/{id}/publish → 500
POST /_emdash/api/content/pages/{id}/publish → 500
POST /_emdash/api/content/videos/{id}/publish → 500

Browser console:
Failed to load resource: the server responded with a status of 500
/_emdash/api/content/posts/{id}/publish
```

### PR DESCRIPTION
**Pull request by mvanhorn**
## What does this PR do?

Removes the FTS5 `integrity-check` INSERT from `verifyAndRepairIndex()` in `packages/core/src/search/fts-manager.ts`. This command corrupts D1's FTS5 shadow tables on every Worker cold start, causing all content publishing to fail with `SQLITE_CORRUPT_VTAB`.

The row-count mismatch check (Check 1) is retained -- it catches the most common corruption case without triggering D1's shadow table bug.

Closes #252

## Type of change

- [x] Bug fix
- [ ] Feature (requires [approved Discussion](https://github.com/emdash-cms/emdash/discussions/categories/ideas))
- [ ] Refactor (no behavior change)
- [ ] Documentation
- [ ] Performance improvement
- [ ] Tests
- [ ] Chore (dependencies, CI, tooling)

## Checklist

- [x] I have read [CONTRIBUTING.md](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md)
- [x] `pnpm typecheck` passes
- [x] `pnpm --silent lint:json | jq '.diagnostics | length'` returns 0
- [x] `pnpm test` passes (or targeted tests for my change)
- [x] `pnpm format` has been run
- [ ] I have added/updated tests for my changes (if applicable)
- [x] I have added a [changeset](https://github.com/emdash-cms/emdash/blob/main/CONTRIBUTING.md#changesets) (if this PR changes a published package)
- [ ] New features link to an approved Discussion: https://github.com/emdash-cms/emdash/discussions/...

## AI-generated code disclosure

- [x] This PR includes AI-generated code

## Details

The root cause is at `fts-manager.ts:407`:

```sql
INSERT INTO "ftsTable"("ftsTable") VALUES('integrity-check')
```

This FTS5 command is safe on standard SQLite but corrupts D1's shadow tables. Once corrupted, every content UPDATE fires FTS triggers that fail with `SQLITE_CORRUPT_VTAB`, blocking all publishing across all collections.

The fix removes the integrity-check entirely. The row-count mismatch check already handles the primary corruption case (count drift between content and FTS tables). The integrity-check was meant to catch subtle shadow table inconsistencies, but on D1 it causes the very corruption it was designed to detect.

Note: 3 pre-existing auth test failures on main (invite, magic-link, signup URL assertions) are unrelated to this change.

This contribution was developed with AI assistance (Codex).

### CODE REVIEW

File: packages/core/src/search/fts-manager.ts [hunk 1]
```diff
@@ -401,20 +399,8 @@ export class FTSManager {
...
-			console.warn(`FTS integrity check failed for "${collectionSlug}". Rebuilding index.`);
-			const fields = await this.getSearchableFields(collectionSlug);
-			const config = await this.getSearchConfig(collectionSlug);
-			if (fields.length > 0) {
-				await this.rebuildIndex(collectionSlug, fields, config?.weights);
-			}
-			return true;
-		}
+		// Do not run FTS5 "integrity-check": on D1 it can corrupt FTS shadow tables
+		// and trigger SQLITE_CORRUPT_VTAB failures (see issue #252).
```
Comment (ascorbic) [inline packages/core/src/search/fts-manager.ts]:
```suggestion
```

**Review by ascorbic — APPROVED** [review]
Thanks!

**Comment by mvanhorn** [comment]
Thanks for the merge, @ascorbic!
