### PR TITLE
fix: repair invite flow — URL prefix + registration UI (fixes #67)

### LINKED ISSUE #67: User invite system: wrong URL (missing /_emdash/ prefix) + no UI to complete registration
## Environment

- EmDash version: `0.0.3`
- `@emdash-cms/auth` version: `0.0.1`
- Adapter: Node.js + SQLite (Hetzner VPS)

---

## Bug 1: Invite URL missing `/_emdash/` prefix → 404

**File:** `packages/auth/src/invite.ts` (approx. line 65)

```ts
const url = new URL("/api/auth/invite/accept", config.baseUrl);
```

`config.baseUrl` is passed in as `https://example.com/_emdash` (from `getSiteBaseUrl()`). When constructing `new URL("/api/auth/invite/accept", "https://example.com/_emdash")`, the leading slash on the path is treated as an absolute path, which **replaces** the entire path of the base URL — discarding `/_emdash`.

**Resulting URL (wrong):**
```
https://example.com/api/auth/invite/accept?token=...
```

**Expected URL:**
```
https://example.com/_emdash/api/auth/invite/accept?token=...
```

Since the route is registered at `/_emdash/api/auth/invite/accept`, clicking the invite link returns a **404**.

**Suggested fix** — use a relative path or string concatenation instead:
```ts
const url = new URL(`${config.baseUrl}/api/auth/invite/accept`);
```

---

## Bug 2: `GET /invite/accept` returns raw JSON — no UI to complete registration

**File:** `src/astro/routes/api/auth/invite/accept.ts`

When the invitee visits the invite link (after fixing Bug 1), the `GET` handler validates the token and returns raw JSON:

```json
{"success":true,"email":"user@example.com","role":30,"roleName":"AUTHOR"}
```

There is no redirect to an admin UI page where the user can complete registration. The `POST /invite/complete` endpoint expects a WebAuthn passkey credential — but there is no frontend page to drive that flow.

**Result:** The user is never actually created. Checking the Users section in the admin dashboard confirms no new user appears despite the `success: true` response. The invite flow is effectively non-functional end-to-end.

**Expected behavior:** `GET /invite/accept` should redirect to an admin UI page (e.g. `/_emdash/admin/invite/accept?token=...`) that renders a form for the user to complete registration (set name, register passkey or set password).

---

## Summary

The invite flow has two compounding bugs:
1. The link given to admins to share points to a 404
2. Even after manually correcting the URL, visiting it returns JSON with no UI — and no user is actually created in the database

Both issues make the user invite system completely non-functional on the Node.js adapter.

### PR DESCRIPTION
**Pull request by mohamedmostafa58**
## Summary

Fixes the broken invite system (#67). Based on PR #81 by @SrikanthAlva with the failing test fix applied.

- Fix invite URL construction to point to admin UI page instead of raw API endpoint
- Add InviteAcceptPage for passkey registration
- Fix test assertion to match new URL path

Closes #67

### CODE REVIEW

**Comment by mohamedmostafa58** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nickgraynews** [comment]
Yes please! We need this to work so we can onboard more users to our sites

File: packages/admin/src/lib/api/users.ts [hunk 1]
```diff
@@ -156,6 +156,87 @@ export async function inviteUser(email: string, role?: number): Promise<InviteRe
...
+
+	return parseApiResponse<InviteVerifyResult>(response, "Invite validation failed");
+}
+
+/**
+ * Complete invite registration with passkey credential.
+ *
+ * Uses custom error handling to preserve error codes for the UI.
+ */
+export async function completeInviteSignup(
```
Comment (ascorbic) [inline packages/admin/src/lib/api/users.ts]: Is this used anywhere?

File: packages/core/src/astro/routes/api/auth/invite/register-options.ts [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+		// Get passkey config
+		const url = new URL(request.url);
+		const options = new OptionsRepository(emdash.db);
+		const siteName = (await options.get<string>("emdash:site_title")) ?? undefined;
+		const passkeyConfig = getPasskeyConfig(url, siteName);
+
+		// Generate registration options with a temporary user identity
+		const challengeStore = createChallengeStore(emdash.db);
+		const tempUser = {
+			id: `invite-${Date.now()}`,
```
Comment (ascorbic) [inline packages/core/src/astro/routes/api/auth/invite/register-options.ts]: It's safer to use a ULID for this.

File: packages/admin/src/components/InviteAcceptPage.tsx [hunk 3]
```diff
@@ -0,0 +1,244 @@
...
+				</h2>
+				<p className="text-kumo-subtle mt-2">{message}</p>
+			</div>
+
+			<div className="space-y-2">
+				{code === "USER_EXISTS" ? (
+					<Link to="/login">
+						<Button className="w-full">Sign in instead</Button>
+					</Link>
+				) : (
```
Comment (ascorbic) [inline packages/admin/src/components/InviteAcceptPage.tsx:126]: There's already a "back to login" button below. This would render two buttons with the same link

File: packages/core/src/plugins/email-console.ts [hunk 4]
```diff
@@ -24,8 +24,17 @@ export interface StoredEmail {
...
+ * In-memory store for dev emails.
+ * Uses globalThis so the same array is shared across Vite SSR module
+ * instances (the runtime and the route handler may load separate copies
+ * of this module, but globalThis is always the same object).
+ */
+const GLOBAL_KEY = "__emdash_dev_emails__" as const;
+const storedEmails: StoredEmail[] =
+	((globalThis as Record<string, unknown>)[GLOBAL_KEY] as StoredEmail[] | undefined) ??
+	(((globalThis as Record<string, unknown>)[GLOBAL_KEY] = [] as StoredEmail[]),
+	(globalThis as Record<string, unknown>)[GLOBAL_KEY] as StoredEmail[]);
```
Comment (ascorbic) [inline packages/core/src/plugins/email-console.ts]:
```suggestion
const storedEmails: StoredEmail[] =                                                                                                             
      ((globalThis as Record<string, unknown>)[GLOBAL_KEY] ??= []) as StoredEmail[];
```

File: packages/admin/src/components/InviteAcceptPage.tsx [hunk 5]
```diff
@@ -0,0 +1,244 @@
...
+import * as React from "react";
+
+import { validateInviteToken, type InviteVerifyResult } from "../lib/api";
+import { PasskeyRegistration } from "./auth/PasskeyRegistration";
+import { LogoLockup } from "./Logo.js";
+
+// ============================================================================
+// Types
+// ============================================================================
+
```
Comment (ascorbic) [inline packages/admin/src/components/InviteAcceptPage.tsx]: There are a lot of redundant comments like this. The AGENTS.md says that there shouldn't be comments where the code is self-explanatory

File: packages/admin/src/components/InviteAcceptPage.tsx [hunk 6]
```diff
@@ -0,0 +1,244 @@
...
+export function InviteAcceptPage() {
+	const [step, setStep] = React.useState<InviteStep>("verify");
+	const [error, setError] = React.useState<string | undefined>();
+	const [errorCode, setErrorCode] = React.useState<string | undefined>();
+	const [isLoading, setIsLoading] = React.useState(true);
+	const [inviteData, setInviteData] = React.useState<InviteVerifyResult | null>(null);
+	const [token, setToken] = React.useState<string | null>(null);
+
+	React.useEffect(() => {
+		const params = new URLSearchParams(window.location.search);
```
Comment (ascorbic) [inline packages/admin/src/components/InviteAcceptPage.tsx]: This is a TanStack Router page, so you should use `useSearch`

**Review by ascorbic — COMMENTED** [review]
Thanks! Just a few comments

**Review by ascorbic — APPROVED** [review]
Thanks!

**Comment by ascorbic** [comment]
@mohamedmostafa58 Can you fix the e2e test failures?
